version: '3.8'

services:

  php:
    container_name: local-php
    build: docker/php
    links:
      - postgres
      - redis
    environment:
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      DB_HOST: postgres
      PGPASSWORD: local
    working_dir: /var/www/project
    user: 1000:1000
    volumes:
      - ./:/var/www/project
  nginx:
    container_name: local-nginx
    image: nginx:alpine
    links:
      - php
    working_dir: /var/www/project
    volumes:
      - ./:/var/www/project
      - ./docker/nginx:/etc/nginx/conf.d/
  postgres:
    container_name: local-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    container_name: local-redis
    image: redis:alpine
    user: 1000:1000
    restart: always
    volumes:
        - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
    postgres:
